module Rapyd

  ERROR_CLASS_MAPPING = {
    "PaymentError" => [
      "ERROR_3DS_VERIFICATION_IS_NOT_SUPPORTED",
      "ERROR_CANCEL_PAYMENT",
      "ERROR_CAPTURE_PAYMENT",
      "ERROR_CAPTURE_PAYMENT_FOR_CARD_METHODS_ONLY",
      "ERROR_CREATE_PAYMENT",
      "ERROR_CREATE_PAYMENT_CAPTURE_FOR_CARD_METHODS_ONLY",
      "ERROR_CREATE_PAYMENT_COMPLETE_PAYMENT_URL_NOT_VALID",
      "ERROR_CREATE_PAYMENT_CURRENCY_NOT_SUPPORTED",
      "ERROR_CREATE_PAYMENT_ERROR_PAYMENT_URL_NOT_VALID",
      "ERROR_CREATE_PAYMENT_PERCENTAGE_MUST_BE_BETWEEN_0_AND_100",
      "ERROR_CREATE_PAYMENT_SPLIT_MISSING_AMOUNT_OR_PERCENTAGE",
      "ERROR_FEES_ONLY_ALLOWED_FOR_EWALLET_TRANSACTIONS",
      "ERROR_FX_FEE_ONLY_ALLOWED_FOR_FX_TRANSACTIONS",
      "ERROR_GET_AMOUNT_AND_PERCENTAGE",
      "ERROR_GET_CUSTOMER_DEFAULT_PAYMENT_METHOD",
      "ERROR_GET_PAYMENT",
      "ERROR_INVALID_FX_FEE_CALC_TYPE",
      "ERROR_INVALID_FX_FEE_VALUE",
      "ERROR_INVALID_NET_FEES",
      "ERROR_INVALID_TRANSACTION_FEE_CALC_TYPE",
      "ERROR_INVALID_TRANSACTION_FEE_FEE_TYPE",
      "ERROR_INVALID_TRANSACTION_FEE_VALUE",
      "ERROR_MISSING_PAYMENT_TOKEN",
      "ERROR_PAYMENT_AMOUNT_HAS_TO_BE_POSITIVE",
      "ERROR_PAYMENT_CAN_NOT_BE_CANCELED",
      "ERROR_PAYMENT_EWALLET_NOT_AN_ARRAY_OR_STRING",
      "ERROR_PAYMENT_FIELD_NAME_NOT_KNOWN",
      "ERROR_PAYMENT_FX_INVALID_EXPIRATION",
      "ERROR_PAYMENT_INVALID_AMOUNT",
      "ERROR_PAYMENT_METHOD_TYPE_DOES_NOT_SUPPORT_FX",
      "ERROR_PAYMENT_METHOD_TYPE_DOES_NOT_SUPPORT_PAYMENT_CANCELLATION",
      "ERROR_PAYMENT_METHODS_GET",
      "ERROR_PAYMENT_MORE_THAN_TWO_AMOUNT_OR_PERCENTAGE_ARE_MISSING",
      "ERROR_PAYMENT_NOT_FOUND",
      "ERROR_PAYMENT_NUMBER_OF_EWALLETS_EXCEEDED",
      "ERROR_PAYMENT_PERCENT_MUST_BE_BETWEEN_0_TO_100",
      "ERROR_PAYMENT_PERCENTAGE_HAS_TO_BE_POSITIVE",
      "ERROR_PAYMENT_SPLIT_AMOUNT_EXCEEDS_PAYMENT_AMOUNT",
      "ERROR_SPLIT_PAYMENT_DUPLICATE_EWALLET",
      "ERROR_TRANSACTION_FEE_INVALID_AMOUNT",
      "ERROR_UPDATE_PAYMENT",
      "ERROR_USING_TOKEN",
      "IDEMPOTENCY_ERROR",
      "INVALID_COMPLETE_PAYMENT_URL",
      "INVALID_ERROR_PAYMENT_URL",
      "INVALID_PAYMENT",
      "MISSING_PAYMENT",
      "MISSING_PAYMENT_METHOD_REQUIRED_FIELD",
      "PAYMENT_CAPTURED_BEFORE",
      "UNKNOWN_PAYMENT_METHOD_FIELDS",
    ],
    "GroupPaymentError" => [
      "ERROR_CASH_NOT_SUPPORTED_FOR_GROUP_PAYMENT",
      "ERROR_CREATE_GROUP_PAYMENT_EXCEEDED_MAX_PARTICIPANTS",
      "ERROR_CREATE_GROUP_PAYMENT_INVALID_EXPIRATION",
      "ERROR_CREATE_GROUP_PAYMENT_INVALID_PAYMENTS",
      "ERROR_CREATE_GROUP_PAYMENT_MISSING_CURRENCY",
      "ERROR_CREATE_GROUP_PAYMENT_MISSING_PAYMENTS",
      "ERROR_CREATE_GROUP_PAYMENT_PARTICIPANTS_LESS_THAN_MIN",
      "ERROR_DIFFERENT_COUNTRIES_NOT_SUPPORTED_FOR_GROUP_PAYMENT",
      "ERROR_DIFFERENT_CURRENCIES_NOT_SUPPORTED_FOR_GROUP_PAYMENT",
      "ERROR_ESCROW_NOT_SUPPORTED_FOR_GROUP_PAYMENT",
      "ERROR_FX_NOT_SUPPORTED_FOR_GROUP_PAYMENT",
      "ERROR_GET_GROUP_PAYMENT",
      "ERROR_GROUP_PAYMENT_CAN_NOT_BE_CANCELED",
      "ERROR_GROUP_PAYMENT_CAN_NOT_BE_REFUNDED",
      "ERROR_GROUP_PAYMENT_NO_FAILED_PAYMENTS_TO_REPLACE",
      "ERROR_GROUP_PAYMENT_PAYMENT_AMOUNT_EXCEEDS_FAILED_PAYMENTS_TOTAL_AMOUNT",
      "ERROR_INVALID_GROUP_PAYMENT",
      "ERROR_MISSING_GROUP_PAYMENT",
      "ERROR_REFUND_GROUP_PAYMENT_INVALID_AMOUNT",
    ],
    "RefundError" => [
      "ERROR_ADDING_REFUND",
      "ERROR_CREATE_REFUND",
      "ERROR_GET_EWALLET_NOT_ENOUGH_FUNDS",
      "ERROR_UPDATE_REFUND",
      "INVALID_REFUND",
      "INVALID_REFUND_STATUS",
      "INVALID_REFUND_TOKEN",
      "PAYMENT_NOT_COMPLETED",
    ],
    "CustomerError" => [
      "CREDIT_CARD_EXISTS",
      "DELETE_CUSTOMER_DEFAULT_PAYMENT_METHOD_NOT_ALLOWED",
      "ERROR_CREATE_CLIENT_DETAILS",
      "ERROR_CREATE_CUSTOMER",
      "ERROR_DEFAULT_PAYMENT_METHOD_BELONGS_TO_DIFFERENT_CUSTOMER",
      "ERROR_DELETE_CUSTOMER",
      "ERROR_DELETE_CUSTOMER_DISCOUNT",
      "ERROR_GET_CUSTOMER",
      "ERROR_GET_PAYMENT_METHOD",
      "INVALID_CUSTOMER",
      "INVALID_CUSTOMER_EMAIL",
      "INVALID_CUSTOMER_ID",
      "INVALID_CUSTOMER_NAME",
      "INVALID_CUSTOMER_PHONE_NUMBER",
      "INVALID_REQUIRED_PAYMENT_METHOD_FIELDS",
      "INVALID_TOKENS_LIMIT",
    ],
    "AddressError" => [
      "ERROR_ADDRESS_GET",
      "INVALID_ADDRESS_ID",
      "INVALID_ADDRESS_LINE_1",
      "INVALID_ADDRESS_LINE_2",
      "INVALID_ADDRESS_NAME",
      "INVALID_ADDRESS_PHONE_NUMBER",
      "INVALID_ADDRESS_ZIP",
      "INVALID_ADDRESSES_FORMAT",
      "INVALID_CITY",
      "INVALID_CUSTOMER_ZIP",
      "INVALID_STATE",
    ],
    "PaymentMethodError" => [
      "CREATE_CARD_TYPE_REQUIRES_ONLY_ONE_OF_FIELDS_OR_TOKEN",
      "ERROR_CREATE_PAYMENT_METHOD",
      "ERROR_DELETE_PAYMENT_METHOD_FROM_WRONG_CUSTOMER",
      "ERROR_GET_PAYMENT_METHOD_TYPE",
      "ERROR_UPDATE_CARD_CVV_NOT_UPDATABLE",
      "ERROR_UPDATE_PAYMENT_METHOD",
      "INVALID_CVV_ONLY_DIGITS_ALLOWED",
      "INVALID_PAYMENT_METHOD",
      "INVALID_PAYMENT_METHOD_REQUIRED_FIELD",
      "INVALID_PAYMENT_METHOD_TYPE",
      "INVALID_REQUIRED_PAYMENT_METHOD_FIELDS",
      "MISSING_PAYMENT_METHOD_REQUIRED_FIELD",
      "PAYMENT_METHOD_FIELD_NOT_UPDATABLE",
      "UNKNOWN_PAYMENT_METHOD_FIELD",
    ],
    "TokenError" => [
      "ERROR_CREATE_PII_TOKEN",
      "ERROR_CREATING_TOKEN",
      "ERROR_RETRIEVE_TOKEN_NOT_FOUND",
      "INVALID_BANK_ACCOUNT_CURRENCY",
      "INVALID_BANK_ACCOUNT_HOLDER_NAME",
      "INVALID_BANK_ACCOUNT_HOLDER_TYPE",
      "INVALID_BANK_NAME",
      "INVALID_HOLDER_COUNTRY",
      "INVALID_PAYMENT_METHOD_TYPE_FOR_CARD_TOKENIZATION",
      "INVALID_TOKEN_TYPE",
      "MISSING_TOKEN_DATA",
      "MISSING_TOKEN_TYPE",
    ],
    "PayoutError" => [
      "ERROR_CANCEL_PAYOUT",
      "ERROR_CONFIRM_PAYOUT",
      "ERROR_CREATE_BENEFICIARY_COUNTRY_NOT_VALID",
      "ERROR_CREATE_BENEFICIARY_CURRENCY_NOT_VALID",
      "ERROR_CREATE_PAYOUT",
      "ERROR_CREATE_SENDER_COUNTRY_NOT_VALID",
      "ERROR_CREATE_SENDER_CURRENCY_NOT_VALID",
      "ERROR_DELETE_PAYOUT_BENEFICIARY",
      "ERROR_EXPIRATION_SENT_FOR_NON_CASH_PAYOUT",
      "ERROR_GET_BENEFICIARY",
      "ERROR_GET_PAYER",
      "ERROR_INVALID_PAYOUT_BENEFICIARY_ENTITY_TYPE",
      "ERROR_INVALID_PAYOUT_SENDER_ENTITY_TYPE",
      "ERROR_LOCATION_PROVIDED_FOR_PAYOUT_THAT_IS_NOT_LOCATION_SPECIFIC",
      "ERROR_MISSING_PAYOUT_AMOUNT",
      "ERROR_MISSING_PAYOUT_BENEFICIARY_COUNTRY",
      "ERROR_MISSING_PAYOUT_BENEFICIARY_ENTITY_TYPE",
      "ERROR_MISSING_PAYOUT_CURRENCY",
      "ERROR_MISSING_PAYOUT_LOCATION",
      "ERROR_MISSING_PAYOUT_METHOD_TYPE",
      "ERROR_MISSING_PAYOUT_SENDER_COUNTRY",
      "ERROR_MISSING_PAYOUT_SENDER_CURRENCY",
      "ERROR_MISSING_PAYOUT_SENDER_ENTITY_TYPE",
      "ERROR_MISSING_PAYOUT_UPDATE_FIELDS",
      "ERROR_PAYOUT_CURRENCY_NOT_SUPPORTED",
      "ERROR_PAYER_DETAILS_IN_REQUEST_AND_SAVED_PAYER_DETAILS_MISMATCH",
      "ERROR_PAYOUT_AMOUNT_NOT_WITHIN_RANGE_OF_PAYOUT_METHOD_TYPE",
      "ERROR_PAYOUT_CURRENCY_NOT_SUPPORTED",
      "ERROR_PAYOUT_NOT_CANCELABLE",
      "ERROR_UNSUPPORTED_PAYOUT_CURRENCY_OR_COUNTRY",
      "ERROR_VALIDATE_PAYOUT_BENEFICIARY",
      "ERROR_UPDATE_NON_ACTIVE_PAYOUT",
      "INVALID_BENEFICIARY_PAYOUT_ENTITY_TYPE",
      "INVALID_DESTINATION_CURRENCY",
      "INVALID_PAYER_FIELDS",
      "INVALID_PAYER_PAYOUT_ENTITY_TYPE",
      "INVALID_PAYOUT",
      "INVALID_PAYOUT_CURRENCIES",
      "INVALID_PAYOUT_METHOD_TYPE",
      "INVALID_PAYOUT_TYPE",
      "MISSING_PAYOUT_BENEFICIARY_COUNTRY",
      "PAYOUT_METHOD_TYPE_BENEFICIARY_COUNTRY_MISMATCH",
    ],
    "WalletError" => [
      "BUSINESS_DETAILS_NOT_ALLOWED_FOR_PERSONAL_CONTACT",
      "CANCEL_TRANSACTION_ERROR",
      "COMPLETE_TRANSACTION_ERROR",
      "CREATE_PERSONAL_WALLET_REQUIRES_PERSONAL_CONTACT",
      "CUSTOMER_ALREADY_ASSIGNED_TO_EWALLET",
      "ERROR_AMOUNT_EXCEEDS_DESTINATION_EWALLET_LIMIT",
      "ERROR_AMOUNT_EXCEEDS_DESTINATION_EWALLET_LIMIT_BY_MERCHANT_CONTROLLED_PARAMETERS",
      "ERROR_CREATE_BANK_ACCOUNT_TRANSFER",
      "ERROR_CREATE_EWALLET_CONTACT",
      "ERROR_CREATE_TRANSFER",
      "ERROR_CREATE_USER_EWALLET_REFERENCE_ID_ALREADY_EXISTS",
      "ERROR_DELETE_EWALLET_BUSINESS",
      "ERROR_DELETE_EWALLET_CONTACT",
      "ERROR_EWALLET_ACCOUNT_LIMIT_EXCEEDS_CURRENT_BALANCE",
      "ERROR_EWALLET_BUSINESS_DETAILS_NOT_SUPPORTED",
      "ERROR_EWALLET_CONTACT_NOT_FOUND",
      "ERROR_EWALLET_DISABLED",
      "ERROR_EWALLET_LIMIT_NOT_VALID",
      "ERROR_EWALLET_SOURCE_PHONE_NUMBER_NOT_FOUND",
      "ERROR_EWALLET_TRANSFER_DESTINATION_EWALLET_DISABLED",
      "ERROR_EWALLET_TRANSFER_ID_NOT_FOUND",
      "ERROR_EWALLET_TRANSFER_RESPONSE_STATUS_NOT_PENDING",
      "ERROR_EWALLET_TRANSFER_SOURCE_EWALLET_DISABLED",
      "ERROR_EWALLET_TRANSFER_SOURCE_EWALLET_NOT_FOUND",
      "ERROR_FIRST_NAME_CONTAINS_ILLEGAL_CHARS",
      "ERROR_GET_EWALLET",
      "ERROR_GET_EWALLET_BUSINESS",
      "ERROR_GET_EWALLET_CONTACT",
      "ERROR_GET_TRANSACTION",
      "ERROR_GET_USER",
      "ERROR_INVALID_EWALLET",
      "ERROR_LAST_NAME_CONTAINS_ILLEGAL_CHARS",
      "ERROR_PAYCODE_AND_REFUND_CODE_OBSOLETE",
      "ERROR_RESPONSE_TRANSFER",
      "ERROR_TRANSFER_FUNDS_DESTINATION_AND_SOURCE_CANNOT_BE_THE_SAME",
      "ERROR_TRANSFER_RESPONSE_INVALID_DETAILS",
      "ERROR_TRANSFER_RESPONSE_PREVIOUSLY_CANCELED",
      "ERROR_TRANSFER_RESPONSE_PREVIOUSLY_DECLINED",
      "ERROR_UPDATE_EWALLET_TYPE",
      "ERROR_UPDATE_FUNDS",
      "ERROR_UPDATE_USER",
      "EWALLET_BUSINESS_DETAILS_ADDRESS_LINE1_NOT_VALID",
      "EWALLET_BUSINESS_DETAILS_ADDRESS_NAME_NOT_VALID",
      "EWALLET_UPDATED_WITH_NO_BUSINESS_DETAILS_DUE_TO_INVALID_ADDRESS",
      "INVALID_ADDRESS_FORMAT",
      "INVALID_EMAIL",
      "INVALID_EWALLET_BUSINESS_ENTITY_TYPE",
      "INVALID_EWALLET_BUSINESS_NAME",
      "INVALID_EWALLET_BUSINESS_REGISTRATION_NUMBER",
      "INVALID_EWALLET_BUSINESS_SUB_CATEGORY",
      "INVALID_EWALLET_CONTACT_TYPE",
      "INVALID_EWALLET_INDUSTRY_CATEGORY",
      "INVALID_EWALLET_TYPE",
      "INVALID_GENDER",
      "INVALID_HOUSE_TYPE",
      "INVALID_LAST_NAME",
      "INVALID_MARITAL_STATUS",
      "INVALID_MIDDLE_NAME",
      "INVALID_SECOND_LAST_NAME",
      "INVALID_SOURCE_CURRENCY",
      "INVALID_TRANSFER_DETAILS",
      "INVALID_TRANSFER_STATUS",
      "MISSING_EWALLET_BUSINESS_DETAILS",
      "MISSING_EWALLET_CONTACT_TYPE",
      "MISSING_EWALLET_ID",
      "MISSING_EWALLET_TOKEN",
      "MISSING_PHONE_NUMBER_OR_EWALLET_ID",
      "NOT_ENOUGH_FUNDS",
      "TRANSFER_DESTINATION_USER_ID_IS_INVALID",
    ],
    "BankAccountObjectError" => [
      "ERROR_CREATE_BANK_ACCOUNT",
      "ERROR_CREATE_BANK_ACCOUNT_FIELD",
      "ERROR_DELETE_BANK_ACCOUNT",
      "ERROR_GET_BANK_ACCOUNT",
      "ERROR_GET_BANK_ACCOUNT_REQUIRED_DETAILS",
      "INVALID_BANK_ACCOUNT",
      "INVALID_BANK_COUNTRY",
      "INVALID_BENEFICIARY_COUNTRY",
    ],
    "IdentityVerificationError" => [
      "ERROR_ID_VERIFICATION",
      "ERROR_ID_VERIFICATION_BACK_SIDE_IMAGE_ENCODING_INVALID",
      "ERROR_ID_VERIFICATION_BACK_SIDE_IMAGE_MIME_TYPE_INVALID",
      "ERROR_ID_VERIFICATION_BACK_SIDE_IMAGE_MISSING",
      "ERROR_ID_VERIFICATION_DUPLICATE_REFERENCE_ID",
      "ERROR_ID_VERIFICATION_IMAGE_NOT_VALID",
      "ERROR_ID_VERIFICATION_INVALID_DOCUMENT_TYPE",
      "ERROR_ID_VERIFICATION_INVALID_EWALLET",
      "ERROR_ID_VERIFICATION_INVALID_FACE_IMAGE_ENCODING",
      "ERROR_ID_VERIFICATION_INVALID_FACE_IMAGE_MIME_TYPE",
      "ERROR_ID_VERIFICATION_INVALID_FRONT_SIDE_IMAGE_ENCODING",
      "ERROR_ID_VERIFICATION_INVALID_FRONT_SIDE_IMAGE_MIME_TYPE",
      "ERROR_ID_VERIFICATION_INVALID_REFERENCE_ID",
      "ERROR_ID_VERIFICATION_MISSING_BACK_SIDE_IMAGE",
      "ERROR_ID_VERIFICATION_MISSING_COUNTRY",
      "ERROR_ID_VERIFICATION_MISSING_DOCUMENT_TYPE",
      "ERROR_ID_VERIFICATION_MISSING_EWALLET",
      "ERROR_ID_VERIFICATION_MISSING_EWALLET_ID",
      "ERROR_ID_VERIFICATION_MISSING_FACE_IMAGE",
      "ERROR_ID_VERIFICATION_MISSING_FRONT_SIDE_IMAGE",
      "ERROR_ID_VERIFICATION_MISSING_REFERENCE_ID",
      "INVALID_DATE_OF_BIRTH",
      "INVALID_IDENTIFICATION_NUMBER",
      "INVALID_IDENTIFICATION_TYPE",
      "INVALID_IMAGE_URL",
    ],
    "DocumentParsingError" => [
      "ERROR_DOCUMENT_VERIFICATION_DUPLICATE_REFERENCE_ID",
      "ERROR_DOCUMENT_VERIFICATION_INVALID_COUNTRY",
      "ERROR_DOCUMENT_VERIFICATION_INVALID_DOCUMENT",
      "ERROR_DOCUMENT_VERIFICATION_INVALID_IMAGE",
      "ERROR_DOCUMENT_VERIFICATION_INVALID_IMAGE_ENCODING",
      "ERROR_DOCUMENT_VERIFICATION_INVALID_PAGE_LIMIT",
      "ERROR_DOCUMENT_VERIFICATION_INVALID_PAGE_NUMBER",
      "ERROR_DOCUMENT_VERIFICATION_INVALID_REFERENCE_ID",
      "ERROR_DOCUMENT_VERIFICATION_MISSING_EWALLET",
      "ERROR_DOCUMENT_VERIFICATION_MISSING_REFERENCE_ID",
      "ERROR_DOCUMENT_VERIFICATION_TRANSACTION_ALREADY_FINALIZED",
      "ERROR_GET_DOCUMENT",
      "ERROR_MISSING_DOCUMENT",
    ],
    "AuthenticationError" => [
      "UNAUTHENTICATED_API_CALL",
    ]
  }

  class RapydError < StandardError

    attr_reader :message, :http_status, :http_body, :http_headers, :json_body

    def initialize(params = {})
      params.each do |key, value|
        instance_variable_set("@#{key}", value)
      end
    end

    def to_s
      status_string = @http_status.nil? ? "" : "(Status #{@http_status}) "
      "#{status_string}#{@message}"
    end

  end

  class PaymentError < RapydError
  end

  class GroupPaymentError < RapydError
  end

  class RefundError < RapydError
  end

  class CustomerError < RapydError
  end

  class AddressError < RapydError
  end

  class PaymentMethodError < RapydError
  end

  class TokenError < RapydError
  end

  class PayoutError < RapydError
  end

  class WalletError < RapydError
  end

  class BankAccountObjectError < RapydError
  end

  class IdentityVerificationError < RapydError
  end

  class DocumentParsingError < RapydError
  end

  class ApiConnectionError < RapydError
  end

  class ParseError < RapydError
  end

  class AuthenticationError < RapydError
  end

end